### ISSUE TITLE
Input manual/custom freesurfer segmentations as a substitute for JLF output

### ISSUE THREAD

**Issue by ericfeczko** [nipreps/nibabies#166]
### A short summary of what you would like to see in *NiBabies*.

We have infants with gold standard manually edited/externally created freesurfer segmentations that we would like to use in place of the segmentation step. Preferably, this could be implemented as a flag for a "manual" segmentation that would bypass the current JLF-stage. 

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
One thing I've wanted to do in fMRIPrep is to allow passing one or more directories of pre-computed derivatives. Suppose we get a dataset like this:

```
dataset/
    derivatives/
        myseg/
            dataset_descriptions.json
            sub-01/
                anat/
                    sub-01_desc-manual_dseg.nii.gz
    dataset_description.json
    sub-01/
        ...
```

We can then call:

```
nibabies dataset/ /path/to/output/ participant --derivatives dataset/derivatives/myseg/ [OPTIONS]
```

By organizing as a BIDS derivative, we could query for any of a number of pre-computed derivatives (segmentations, masks, surfaces) through a single mechanism, rather than having a specific flag for each thing someone might want to pre-compute.

This also leaves the possibility of having separately stored datasets, that can be referenced by DOI in the provenance. (Might not happen much...)

**Comment by ericfeczko** [comment]
I like that -- its a cool hack that allows for easy scalability without requiring too much on the user. Furthermore, it standardizes "custom" inputs in a manner that's sensible.

How big of a scope is such a request?

**Comment by mgxd** [comment]
I like leaning into BIDS derivatives - we should discuss this in more detail in tomorrow's meeting

**Comment by effigies** [comment]
> How big of a scope is such a request?

IMO very small. The biggest issue is going to be that it puts a burden on users to correctly organize a derivatives directory, as there is not yet validator support.

**Comment by ericfeczko** [comment]
Awesome! Lets definitely chat about this in tomorrows meeting for sure :)

**Comment by ericfeczko** [comment]
Hey all! 

Thanks again for describing the idea in detail over the meeting two weeks ago. I love the scalability of leaning into the derivatives like you suggest :) 

I wanted to know what the timeline might be for these changes, given the holidays are upon us? If there are any obstacles that I can help with, I would be happy to be of assistance :)

Thanks again!
