### ISSUE TITLE
Allow T2w-only brain extraction

### ISSUE THREAD

**Issue by marilyncyr** [nipreps/nibabies#172]
### A short summary of what you would like to see in *NiBabies*.

In cases where the T1 is missing or unusable, could we use the T2 alone for brain extraction?

### Do you have any interest in helping implement the feature?

No :(

### Add any additional information or context about the request here.

We're having issues with babies frequently waking up during collection of the T1 (which is very loud on our GE scanner) and so we're missing T1s for many subjects. Given that T2 typically show better contrast in infants, could a T2 be sufficient to provide adequate segmentation? We tried creating a "fake T1" using the T2: fakeT1= -(T2 - max(T2)) and feeding that to the pipeline as a T1 along with the T2, but that didn't yield good outputs. Has anyone has run into a similar issue? Any suggestions? Fix?

**Comment by ericfeczko** [comment]
@marilyncyr  -- Unfortunately, this is not a trivial issue -- depending on the age of the infant. Both T1-only and T2-only HCP style pipelines struggle with infant data due to the contrast spin inversion effect between 0-8  months of age; effectively T1 captures contrast better than T2 in certain parts of the brain, and the benefits shift regionally as a function of age.

**Comment by mgxd** [comment]
Single anatomical processing is available as of `23.1.0`
