### ISSUE TITLE
Anat surface outputs not aligned to subject-space T1w

### ISSUE THREAD

**Issue by madisoth** [nipreps/nibabies#222]
### What happened?

Anatomical surface outputs are not aligned to the subject-space T1w as in fMRIPrep. They do appear aligned if the inverse of the "from-fsnative_to-T1w" xfm is applied to the surfaces.
  
The surfaces in the infant-freesurfer dir look correct overlaid on brain.mgz.

### What command did you use?

```shell
nibabies_22.0.2.sif /data /out participant --age-months 1 \
--output-spaces MNIInfant:cohort-1 \
--derivatives /derivatives \
--cifti-output 91k
```

### What version of NiBabies are you using?

22.0.2

**Comment by mgxd** [comment]
I think this stems from a bad `fsnative2t1w_xfm` - we may want to generate it like [smriprep does it](https://github.com/nipreps/smriprep/blob/a60259c5c06d4519114f77aa1223cb891cbcf411/smriprep/workflows/surfaces.py#L226-L228), rather than just taking the one calculated by `infant_recon_all`.

BTW, this is probably why we were seeing https://github.com/nipreps/nibabies/issues/97, moving to the FSL based bbr hid this problem since it is not relying on that transform.
