### ISSUE TITLE
Warnings generated by `warnings.warn` are not shown in the terminal output (?)

### ISSUE THREAD

**Issue by scott-huberty** [nipreps/nibabies#352]
### What happened?

Let me know if this isn't the case for others, or if I'm missing something, but at least on my end, any warnings in the `Nibabies` codebase that are generated using `warnings.warn...` don't actually make it to my terminal output when running `Nibabies`.

For example, when running a file, the code was reaching this if statement below, but the warning didn't actually print in the terminal:

https://github.com/nipreps/nibabies/blob/1829514594a7627a39c53cfccd7106b5173a8a6c/nibabies/utils/bids.py#L90-L93

If I swapped out `warnings.warn` for the config logger (like the code below), then the warning will show in the terminal (which makes sense as I assume that is what this cli.logger is meant for):

https://github.com/nipreps/nibabies/blob/1829514594a7627a39c53cfccd7106b5173a8a6c/nibabies/workflows/base.py#L116-L119

Anyways, I think it's helpful to see warnings in the terminal output (it grabs your attention, and I would have realized what was going wrong :slightly_smiling_face: ). Should all uses of `warnings.warn` be replaced by `config.loggers.cli.warning` ?

### What command did you use?

```shell
N.A.
```

### What version of NiBabies are you using?

latest

### Relevant log output

```shell
I cannot find any log files for my run (if any are generated?). I looked into the Nibabies documentation but there is no mention of where one can find log files.
```

**Comment by mgxd** [comment]
well, the reason they're not displaying is we have an explicit catch in the configuration 😄 :

https://github.com/nipreps/nibabies/blob/653491eea1df20490effa3342550e5f464ad6073/nibabies/config.py#L92-L103

Good catch as I had forgotten about this - IIRC, this originated in fmriprep due to some excessively noisy dependencies cluttering the console output. Looking back, I feel like this was a bit of an overcorrection, and we should probably just use a warning filter.

**Comment by mgxd** [comment]
Yep I prefer 1, sprinkling in `warnings.filterwarnings` when needed

**Comment by scott-huberty** [comment]
Alright, I'll try to open a PR in the coming weeks.
